---
#
# https://github.com/marketplace/actions/super-linter
#
name: Lint Code Base

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-format:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
        
